# https://github.com/elastic/elasticsearch-docker
FROM daocloud.io/hadwinzhy/elasticsearch-docker

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
